### PR TITLE
open_images.py quick fix

### PR DESCRIPTION
**Pull request by relh**
next(reader) replacing reader.next()

In Python 3.6.5 there is an AttributeError: 'DictReader' object has no attribute 'next' and this fixes it. #604

### CODE REVIEW

**Comment by hgaiser** [comment]
Strange that it has no `next` method, but this fix seems harmless to me so if it fixes it for you, I'm find with merging this.

@lvaleriu ?

**Comment by lvaleriu** [comment]
I'm using python 2.7 and the actual call "reader.next()" works. Ok for changing that to next(reader) (with a python version switch or direcly since this last call works in python 2.7 too)

**Comment by hgaiser** [comment]
Seeing as it works on both python2 and python3, I don't believe a switch will be necessary. Thanks for the PR!
