### ISSUE TITLE
training

### ISSUE THREAD

**Issue by strWuYaoJu** [fizyr/keras-retinanet#1416]
running: 
           python keras-retinanet/keras_retinanet/bin/train.py --snapshot-path models csv image_labels/train_data.csv image_labels/class.csv --val-annotations image_labels/val_data.csv

error: 
       TypeError: type object got multiple values for keyword argument 'training'

**Comment by gosha20777** [comment]
I've get the same error

**Comment by GlitchBox** [comment]
I've got the same error. Why did it occur?

**Comment by gosha20777** [comment]
@GlitchBox I think that this implementation is not compartable with tf 2.x and keras 2.3.1

You can use my fork of it witch supports the latest tf and keras versions
https://github.com/lacmus-foundation/lacmus

**Comment by GlitchBox** [comment]
@gosha20777 thank you so much!

**Comment by hgaiser** [comment]
A PR to fix compatibility would be welcome :)

**Comment by wenwenwenwenshei** [comment]
use keras==2.3.1

**Comment by GeorgeVJose** [comment]
It was working for me in the beginning, but the problem started when I changed the anchors in the config file. Also tried keras==2.3.1 but the problem still exists.

**Comment by akramaskar** [comment]
Any updates here?
Tried running it with keras==2.3.1 but another error came up
`AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'`

**Comment by Zhejing-Chin** [comment]
I am using: 
!pip install tensorflow==1.14.0
!pip install keras==2.3.0
!pip install numpy==1.16.1

and now my !keras_retinanet/bin/train.py --freeze-backbone --random-transform --weights {'/content/keras-retinanet/_pretrained_model.h5'} --batch-size 8 --steps 500 --epochs 10 csv annotations.csv classes.csv
is finally training epoch

**Comment by udaylunawat** [comment]
Any way to make it work with tensorflow 2.3.0? I've managed to make it work with 2.2.0 though.

**Comment by udaylunawat** [comment]
> Any updates here?
> Tried running it with keras==2.3.1 but another error came up
> `AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'`

Got the same error with tf 2.3 and keras 2.3.1

**Comment by vehansayvazi** [comment]
changing to keras 2.4.0 fixed this for me

**Comment by tleyden** [comment]
`pip install tensorflow==2.3.1 && pip install keras==2.4.0` worked for me and got past the `AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'` error I was getting with tf 2.3 + keras 2.3.1

**Comment by sharathm451** [comment]
> @GlitchBox I think that this implementation is not compartable with tf 2.x and keras 2.3.1
> 
> You can use my fork of it witch supports the latest tf and keras versions
> https://github.com/lacmus-foundation/lacmus

bro could you elaborate plz. I am using imageai.objectdetection and 
got this error.  what does it mean like fork your repo,  is it to download Retinanet model and give a try?
coz I have no idea of downloading tf and keras from git fork.
